// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eycydigvwfqapjxssvqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5Y3lkaWd2d2ZxYXBqeHNzdnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODMxOTUsImV4cCI6MjA2Mzc1OTE5NX0.YbPnhnt0qLAVhffOU5yGBRt-2hMjsc9NEGyeIViwQac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);